apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
  labels:
    app: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-app
        image: yahelsharon/task-app:1.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mongodb://mongo-svc:27017/mydb"